env:
  browser: true
  es2021: true
extends:
  - 'plugin:vue/essential'
  - standard
  - prettier
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - vue
  - prettier
rules: {
  'prettier/prettier': ['error'],
  'global-require': 0,
  'vue/no-use-v-if-with-v-for': 'off',
}
