version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server-base
    working_dir: /code/server
    command: bash -c "python manage.py collectstatic --noinput && gunicorn config.wsgi -b 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - frontend
    environment:
      - "USE_LOCAL_STORAGE=TRUE"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-base
    environment:
      - NODE_ENV=development
    ports:
      - 8080:8080
    volumes:
      - .:/code
      - /code/frontend/node_modules
    working_dir: /code/frontend
    command: npm run serve
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data:
