version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server-base
    working_dir: /code/server
    command: sh launch-dev.sh
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - frontend
    environment:
      - "USE_LOCAL_STORAGE=TRUE"
      - "DJANGO_SECRET_KEY=p=4f_cxdno4qj6itdx!@v%7oij3ma%b_y#422*t(dbpk9^pt08"
      - "DJANGO_DEBUG=True"
      - "DJANGO_SECURE_SSL_REDIRECT=False"
      - "DJANGO_SECURE_HSTS_SECONDS=0"
      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
      - "DJANGO_SECURE_HSTS_PRELOAD=False"
      - "DJANGO_SESSION_COOKIE_SECURE=False"
      - "DJANGO_CSRF_COOKIE_SECURE=False"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-base
    environment:
      - "NODE_ENV=development"
    ports:
      - 8080:8080
    volumes:
      - .:/code
      - /code/frontend/node_modules
    working_dir: /code/frontend
    command: npm run serve
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data:
