version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server-prod
    working_dir: /code/server
    command: bash -c "python manage.py collectstatic --noinput && gunicorn config.wsgi -b 0.0.0.0:8000"
    volumes:
      - .:/code
      - code/server/static/dist
      - code/server/staticfiles
      - code/server/mediafiles
      - code/server/templates/vue
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data:
