name: "anu-website"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  django-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install python dependencies
      working-directory: ./server
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --system
        python manage.py collectstatic --noinput
    - name: Run migrations
      working-directory: ./server
      run: python manage.py migrate
    - name: Run tests
      working-directory: ./server
      run: python manage.py test
