name: "anu-website"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  django-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: psycopg2 prerequisites
      run: sudo apt-get install python-dev libpq-dev
    - name: Install python dependencies
      working-directory: ./server
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --system
        python manage.py collectstatic --noinput
      working-directory: ./server
      run: python manage.py migrate
    - name: Run tests
      run: python server/manage.py test server
